#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go')

if [[ ${STAGED_GO_FILES} == "" ]]; then
    echo "No Go Files to analyse."
else
	echo "$STAGED_GO_FILES" | while read -r file; do
        if [[ -f "$file" ]] ;
        then
            ## format our file
            gofmt -s -w "$file"
            goimports-reviser -file-path "$file" -local weavelab.xyz
            ## add any potential changes from our formatting to the commit
            git add "$file"
            echo "imports sort done for : $file"
        fi
    done
fi